### ISSUE TITLE
Need to handle geoserver's envrionment variable in better way.

### ISSUE THREAD

**Issue by ywkim312** [ncsa/charts#17]
Currently, geoserver's env variables are being used separately in the chart. Make those in the one place so make it to easier to modify or check. 
For example, it is currently like 
```
cors:
  enabled: true

extension:
  install: false
  stableExtension: ""

demoData:
  skip: true

envs:
  extraJavaOpts: "-Xms512m -Xmx2g"
```

but it could be better if it goes like
```
env
  cors:
    enabled: true
  extension:
    install: false
    stableExtension: ""
  demoData:
    skip: true
  extraJavaOpts: "-Xms512m -Xmx2g"
```
and also in the deployment yaml file, it might be better to use something like
```
- name: EXTRA_JAVA_OPTS
   value: {{ .Values.envs.extraJavaOpts | quote }}
{{ with .Values.envs }}
            - name: .key
               value: .value
{{ end }}
```
